### ISSUE TITLE
error when downloading the code

### ISSUE THREAD

**Issue by jyyu99** [hfhoffman1144/Heart-Disease-Prediction#1]
I'm on windows and when I try to download the code chrome says it failed- virus detected

**Comment by hfhoffman1144** [comment]
I recommend cloning the repo via git CLI: https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository#:~:text=Cloning%20an%20Existing%20Repository. I'm not sure why chrome detected a virus.
